def nuc(DNA):
    tot=[]
    counterA=0
    counterC=0
    counterG=0
    counterT=0
    for i in DNA:
        if i =='A':
            counterA+=1

        elif i=='C':
            counterC+=1

        elif i=='G':
            counterG+=1

        else: 
            i=='T'
            counterT+=1
    tot.append(counterA)
    tot.append(counterC)
    tot.append(counterG)
    tot.append(counterT)
    return tot

print (*nuc('CGATCGCGGGATCCCTTACAGGATCAAGTCTCGATCGCATTCCCCTTATGCGCAGCGGGCAATGGAGGTTCCCGAACGTCAATTTTGGTGCCTAGGGTTAATGCATGAGTCATACCCGGACTCCACGGCCCCACGGGATTTCCCATGGGGAACAGGTCTCTGTCTGCCTCGGTAATTTATTGATAAAACCCTTGGCTTCGGGACCGTTACCTTGATGCGGTTAAGCGATGCAGTCCGCCGTCGCGAAGCATCCAACCGCCCAGCTATCCTCTAGGGGAGCATTAGGCGACATCGGATAATAGCTAGTTTGCGGTTCATCCGAACGGGAGTCCCACCGGCCATTGAATGGACGCAACAGCGGCCCCACCGGAGTCATTCTTTGTAGATGCAACTGGATATTCGTGGAATAAGAGCAGTGCTAAACCCTTTCAAGTGAATCCCACCCTTCATAGATGAGGGACTCGACCTGATTTCCTCCAGAACTCTGAAATGTCGTCAAGGCGGGTTGTTGCGCTAATGAATCCATTGGTTCTTCTCTGTCAAGACTTACCGAGGGCCACCCAAGATCCTAACAGCCCCTCTCGTTTGCGTGTAATCCAGCATAAATCTTATCCAATCAAACGTACTTCAACCGACAAACTTGGCAATCCCCTGGGGGGTGGTGCGAAGCTCGGGTGGGTGGGTGTACCGGTATGTAATACTATGGCGCGCGCCTGGGCCCAATTTACTTGGTGTAAGAACCCCATCACAGGCGTGCCGGTCTCCATCGTGTCGATCAACCTCGAACCCCGTACGCGTTACATGGAGTGTCCGCGTCTCCTCATATGCATGAGGGGCTCCCGCTGATCAAGGTAACCGTCGAGACTACACAGGGTCATCCCTTTCGCCATGACCCAGATAGGCGGGAACTCCCCGGGATGTCAATTGAGCAGACGTGAAATGCGCCCAAGCTCGCCGCCTTATAGGACGACGGTCCCAGAGGTAATAGGCAAAATGTA'))