def dna(string):
    dnastring=string[::-1]
    complem=""
    
    for i in range(len(dnastring)):
        if dnastring[i]=='A':
            complem+='T'
        if dnastring[i]=='T':
            complem+='A'
        if dnastring[i]=='C':
            complem+='G'
        if dnastring[i]=='G':
            complem+='C'
            
    return complem
print(dna('TTCTTACAAATTGGAAAGGCGGAAATGAACGATCTACGCATTTATAAGAAAACACACAGAGAGCTAGCGTCATATGTGGCAATCGCGAGATCCGGCTAGGATTAGAATGGAGAATGTAATAAAATATCACCATAAGGAATTGAATCCAGCTTCCAGCAATTGCCACGAAGTCCTGTATTTGCTTATGCCAGCACGATTCGTAACACAAGGATTCCCTTGCCCATGTCCGTCTCTCAAATAATTCTTTGGCGAAGCACGTGCTTCCGTCAACCTTAAGATCATAAAGTCGGAACTAGGCACAAGCATCTACTCGGGACACAATTGTCTCAAGCCGGACTTGTTGGTAACGAGTTCCGAATACTTCTCCCTCATCAGAAGCACATATGAAACCTTAAGGCAACTTCCGCATCGGATAACTAGGTGACTGTAGCTGAACCACTCAGCTACAGCCCCACTCTGTCTCGCTTCGTTGTACTTCATGACAATTACTAGTTGCTGGATACGGAGTTATGTAGACTTAGCCAAAGGTGGCTCAGACACCCCTAGGCATATGCGGGAACGGAGACCGCGAGGTGATAACGCCGCAACCGTTTAGCCGTTCTTGGATAAAGATGTAAAGGCAATCAACTCAGGATCCGGCTTTTGTAGCATTCACAGTATTGCCGGAACCAATGGCTCATCCCATTCGGAACATCGCTACTGTGATGATCGCTGACCGCCATACTATAAGGAGCAGGCATAAACCTACGTATGGCCGCGGGGCACGTACGCCGCGGCCATAGGGCGATAGAAGTTGAATGCGTTCTTCATTGCCTTCCTCTTATAGGTACGTGGTGGAAGGGTCCGGATGCTAGCCTAGGTTGTAGTGTGGGTACTCCCATGGGACTCGGGTTCAAATAGGGCTTCGCTGGAAACGTACACGACTTGGAAGATGCGCGATAAAAGAGATGATTCGTCCTATGGTTGGGAGGGTCGTATACCCACGGG'))